### ISSUE TITLE
Non-HTTP auth

### ISSUE THREAD

**Issue by geoffharcourt** [harrystech/cronut#5]
Is the Harry's team open to building some very simple auth with a mechanism rather than HTTP? I'm proposing to do email/password auth with http://github.com/thoughtbot/clearance, which is much lower overhead than Devise, but still allows for email/password auth for multiple users.

I'm going to end up doing this for our own deployment of Cronut, so wanted to check.

**Comment by werkshy** [comment]
If I had my druthers we'd have a way to use a central directory for apps like this, e.g. LDAP via AWS Directory Services or [Jumpcloud](https://jumpcloud.com/).
